baseURL = "https://axect.github.io"
languageCode = "en-us"
title = "Socialst"
theme = "hello-friend-ng"
paginate = 10
googleAnalytics = "UA-167590700-1"

[params]
    dateform = "Jan 2, 2006"
    dateformShort = "Jan 2"
    dateformNum = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"

    # Subtitle for home
    homeSubtitle = "Mathematics, Physics and Computations"

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Metadata mostly used in document's head
    description = "Socialst: Axect's Blog"
    keywords = "blog, homepage"
    images = [""]

    # Default theme "light" or "dark"
    defaultTheme = "light"

    [[params.social]]
        name = "github"
        url = "https://github.com/Axect"

    [[params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/tae-geun-kim/"

    [[params.social]]
        name = "email"
        url = "mailto:axect@outlook.kr"



[author]
    name = "Axect"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Socialst"
    subtitle = "Axect's Blog"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd /home/axect/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags"
